### ISSUE TITLE
ClassNotFoundException when packaging simulations and submitting the tar archive

### ISSUE THREAD

**Issue by thomaspaulin** [jecklgamis/gatling-server#1]
I'm trying to submit my simulations in a package form to the server per your "Packaging Simulations" section of the readme.

In the readme you mentioned "See `scripts/package-simulations.sh` for reference script." but I see no trace of such a script in the repo, nor in the git commit history. I instead tried to mirror the folder structure laid out so I have the following:

```
gatling-packaged-simulations/
gatling-packaged-simulations/binaries/
gatling-packaged-simulations/simulation/
gatling-packaged-simulations/simulation/com/
gatling-packaged-simulations/simulation/com/example/
gatling-packaged-simulations/simulation/com/example/foo/
gatling-packaged-simulations/simulation/com/example/foo/myapi/
gatling-packaged-simulations/simulation/com/example/foo/myapi/MySimulation.scala
gatling-packaged-simulations/bodies/
gatling-packaged-simulations/resources/
gatling-packaged-simulations/resources/data/
gatling-packaged-simulations/resources/data/myapi/
gatling-packaged-simulations/resources/data/myapi/parameters.csv
```

Unfortunately this doesn't work and I receive the following exceptions:
```
GATLING_HOME is set to /app/gatling-charts-highcharts-bundle-3.5.0
13:20:46.868 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.ClassNotFoundException: com.example.foo.myapi.MySimulation
	at java.com.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:71)
	at scala.util.Try$.apply(Try.scala:210)
	at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:71)
	... 15 common frames omitted
Wrapped by: java.lang.IllegalArgumentException: User defined Simulation class com.example.foo.myapi.MySimulation could not be loaded
	at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:80)
	at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:85)
	at scala.Option.orElse(Option.scala:477)
	at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:85)
	at scala.Option.flatMap(Option.scala:283)
	at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:83)
	at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
	at scala.Option.getOrElse(Option.scala:201)
	at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
	at io.gatling.app.Selection$.apply(Selection.scala:36)
	at io.gatling.app.Runner.run0(Runner.scala:64)
	at io.gatling.app.Runner.run(Runner.scala:52)
	at io.gatling.app.Gatling$.start(Gatling.scala:80)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
	at io.gatling.app.Gatling$.main(Gatling.scala:37)
	at io.gatling.app.Gatling.main(Gatling.scala)
```

I ran the simulation successfully locally so I know it's working which suggests to me it's something in my tar structure being wrong.

Please could you confirm what the `scripts/package-simulations.sh` script was doing and how the folder structures should look?

**Comment by thomaspaulin** [comment]
I believe I've narrowed this down to the 3rd party imports used.

If I run the `BasicSimulation` found on the [Gatling Quickstart](https://gatling.io/docs/gatling/tutorials/quickstart/) all is well. If I add the third party imports I'm using to that same simulation, it crashes.

```
import org.json4s.native.Json
import org.json4s.DefaultFormats
```

This says to me we need to build the simulation files on the Gatling server/fetch the dependencies and set up the classpath before running the simulations.

**Comment by thomaspaulin** [comment]
I fixed this by using the [maven-dependency-plugin](https://stackoverflow.com/a/996915/4427782) to copy my dependency jars into `target/lib`. Next I copied them over to the [Gatling bundle's lib folder](https://gatling.io/docs/gatling/tutorials/installation/) and ran my simulations. Those which included third party dependencies, like those above, ran through as expected when run locally.

**Comment by jecklgamis** [comment]
Hey @thomaspaulin  thanks for raising this issue. Sounds like that's the fastest way to solve your issue atm.  I'll do a spike on this one, looks like packaging the external dependencies (minus Scala + Gatling) using the dependency plugin can be an option. The gatling.sh will just have to  be updated with  the task workspace specific lib to it can keep the Gatling libs untouched.

gatling.sh
```
COMPILER_CLASSPATH="$GATLING_HOME/lib/*:$GATLING_CONF:${USER_LIB_DIR}:"
GATLING_CLASSPATH="$GATLING_HOME/lib/*:$GATLING_HOME/user-files:$GATLING_CONF:${USER_LIB_DIR}:"
```

USER_LIB_DIR can then be exposed in gatling.go

```
func (g *Gatling) RunSimulation(commandOps cmdexec.CommandExecutionOps, task *Task) (*exec.Cmd, error) {
	log.Println("Running simulations from", task.UserFilesDir.BaseDir)
	userFilesDir := task.UserFilesDir
	gatlingSh := fmt.Sprintf("%s/bin/gatling.sh", g.BaseDir)
	cmd := exec.Command(gatlingSh,
		"-s", task.Simulation,
		"--simulations-folder", userFilesDir.Simulations,
		"--resources-folder", userFilesDir.Resources,
		"--results-folder", userFilesDir.Results,
		"--binaries-folder", userFilesDir.Binaries)
	cmd.Env = os.Environ()
	cmd.Env = append(cmd.Env, fmt.Sprintf("JAVA_OPTS=%s", task.JavaOpts))
	cmd.Env = append(cmd.Env, fmt.Sprintf("USER_LIB_DIR=%s/*", userFilesDir.Libraries))
	err := commandOps.ExecuteAndLog(cmd, filepath.Join(task.UserFilesDir.BaseDir, "console.log"))
	return cmd, err
}
```
